// frontend/src/routes/about/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { Footer } from "~/components/core/footer";
import { Navbar } from "~/components/core/navbar";
export default component$(() => {
  return (
    <main class="flex min-h-screen w-full flex-col">
      <Navbar />

      <section class="mx-auto flex max-w-4xl flex-1 flex-col items-center justify-center p-4">
        <div class="flex flex-col space-y-4">
          <div class="flex flex-col rounded border-2 bg-[#1111]/80 p-6">
            <h1 class="mb-4 text-3xl font-bold">About Poopmail</h1>

            <div class="space-y-4">
              <p>
                Poopmail is a temporary email service that allows you to create
                disposable email addresses without registration. Perfect for
                testing, signing up for services, or avoiding spam in your
                primary inbox.
              </p>

              <p>
                This service is a subpart of <strong>tsbin.tech</strong>, a
                temporary file bin project designed to provide ephemeral digital
                resources without the hassle of permanent storage.
              </p>

              <div class="mt-6 border-t-2 pt-4">
                <h2 class="mb-3 text-xl font-semibold">Developer</h2>
                <p>
                  Poopmail is developed and maintained by{" "}
                  <a
                    href="https://github.com/PriyanshuPz"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="font-semibold underline transition-colors hover:text-white/80"
                  >
                    Priyanshu Pz
                  </a>
                  .
                </p>
                <p class="mt-2">
                  The project is open-source and available on{" "}
                  <a
                    href="https://github.com/PriyanshuPz/poopmail"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="font-semibold underline transition-colors hover:text-white/80"
                  >
                    GitHub
                  </a>
                  . Contributions, issues, and feedback are welcome!
                </p>
              </div>

              <div class="mt-6 border-t-2 pt-4">
                <h2 class="mb-3 text-xl font-semibold">Key Features</h2>
                <ul class="space-y-2">
                  <li>Instant temporary email addresses</li>
                  <li>No registration or signup required</li>
                  <li>24-hour automatic expiration</li>
                  <li>No data collection or tracking</li>
                  <li>Open-source and transparent</li>
                  <li>Simple, accessible interface</li>
                </ul>
              </div>

              <div class="mt-6 border-t-2 pt-4">
                <h2 class="mb-3 text-xl font-semibold">Privacy First</h2>
                <p>
                  We do not collect, store, or track any personal information.
                  All mailboxes are completely temporary and will be
                  automatically deleted after 24 hours. Your emails are stored
                  only for the duration of the mailbox lifetime.
                </p>
              </div>

              <div class="mt-6 border-t-2 pt-4">
                <h2 class="mb-3 text-xl font-semibold">Open Source</h2>
                <p>
                  This project is open-source and available for anyone to
                  review, contribute to, or self-host. We believe in
                  transparency and community-driven development.
                </p>
                <p class="mt-2">
                  Built with modern technologies: Qwik, Appwrite, Cloudflare
                  Workers, and deployed on Vercel Edge.
                </p>
              </div>

              <div class="mt-6 border-t-2 pt-4">
                <h2 class="mb-3 text-xl font-semibold">Use Cases</h2>
                <ul class="space-y-2">
                  <li>Testing email functionality in applications</li>
                  <li>Signing up for newsletters without spam</li>
                  <li>One-time verifications</li>
                  <li>Avoiding unwanted marketing emails</li>
                  <li>Quick disposable communication</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
});

export const head: DocumentHead = {
  title: "About | Poopmail",
  meta: [
    {
      name: "description",
      content:
        "Learn about Poopmail - a temporary email service by tsbin.tech. Privacy-focused, open-source, and completely free with no data collection.",
    },
  ],
};

// web/src/routes/about/+page.svelte
<svelte:head>
  <title>About | tsbin Mail</title>
  <meta
    name="description"
    content="About tsbin Mail - a temporary email service by tsbin.tech. Privacy-focused, open-source, and completely free."
  />
</svelte:head>

<main>
  <div class="container">
    <h1>About</h1>

    <section>
      <p>
        tsbin Mail is a privacy-first temporary email service for testing,
        verification, and spam-free communication.
      </p>
      <p>
        It was built to solve a common problem: needing an email address for
        one-time signups or tests without exposing your primary inbox.
      </p>
      <p>
        tsbin Mail takes a privacy-first approach. All mailboxes auto-delete
        after 24 hours. No accounts. No tracking. No permanent storage.
      </p>
      <p>
        The philosophy is straightforward: utility software should be fast,
        predictable, and respect your privacy by default.
      </p>
    </section>

    <section>
      <h2>Design Principles</h2>
      <p>tsbin Mail follows a set of core principles:</p>
      <ul>
        <li>24-hour auto-deletion — no permanent storage</li>
        <li>No registration — instant email addresses</li>
        <li>Zero tracking — no analytics or telemetry</li>
        <li>Open source — transparent and auditable</li>
        <li>Minimal feature set — does one thing well</li>
      </ul>
      <p>These principles guide every technical decision.</p>
    </section>

    <section>
      <h2>How It Works</h2>
      <p>
        Create a temporary email address instantly. Receive emails for 24 hours.
        After that, the mailbox and all messages are permanently deleted.
      </p>
      <p>
        No signup required. No email verification. No password to remember. Just
        a simple, disposable email address.
      </p>
      <p>
        Perfect for testing applications, signing up for newsletters, or any
        situation where you need an email address but don't want spam.
      </p>
    </section>

    <section>
      <h2>About tsbin</h2>
      <p>tsbin is a home for small, useful software.</p>
      <p>
        It's a collection of utilities built with a focus on simplicity,
        privacy, and long-term reliability.
      </p>
      <p>
        Each tool serves a clear purpose without unnecessary features or
        dependencies.
      </p>
      <p>No engagement loops. No growth tactics. Just tools.</p>
    </section>

    <section>
      <h2>About P8labs</h2>
      <p>
        P8labs is an independent technology lab exploring developer tools, AI
        systems, and infrastructure-style software.
      </p>
      <p>
        The lab focuses on building practical systems that solve real problems
        without unnecessary complexity.
      </p>
      <p>
        Projects are designed for durability over novelty, utility over
        attention.
      </p>
    </section>

    <section>
      <h2>Technical Details</h2>
      <p>tsbin Mail is built using modern web standards and SvelteKit.</p>
      <p>
        The codebase is intentionally small and focused. Backend uses Appwrite
        for database operations.
      </p>
      <p>
        Email receiving is handled through standard SMTP protocols. All data is
        automatically purged after 24 hours.
      </p>
      <p>
        The entire system is designed to be maintainable and reliable for years.
      </p>
    </section>

    <section>
      <h2>Open Source</h2>
      <p>tsbin Mail is fully open source under a permissive license.</p>
      <p>You can review, modify, and distribute the code freely.</p>
      <p>Contributions are welcome through GitHub pull requests.</p>
      <p>
        <a
          href="https://github.com/P8labs/tsbin-mail"
          target="_blank"
          rel="noopener">View repository →</a
        >
      </p>
    </section>

    <section>
      <h2>Support</h2>
      <p>
        tsbin Mail is provided without formal support, but we do our best to
        address issues and feedback.
      </p>
      <p>
        For bugs, feature requests, or questions, please open an issue on
        GitHub.
      </p>
      <p>
        <a
          href="https://github.com/P8labs/tsbin-mail/issues"
          target="_blank"
          rel="noopener">GitHub Issues →</a
        >
      </p>
    </section>

    <section>
      <h2>Philosophy</h2>
      <p>
        Software should be quiet infrastructure that disappears until needed.
      </p>
      <p>
        The best tools are those you don't think about — they simply work when
        required.
      </p>
      <p>This is the standard tsbin Mail aims to meet.</p>
    </section>
  </div>
</main>
